Dev
MobileUpLLC/KMM-Form-Validation pull request #1
Opened 2023-02-02 08:00 UTC by Takexito

2023-02-02 10:46 UTC, aartikov requested changes

2023-02-02 10:46 UTC, aartikov commented on gradle.properties
> +kotlin.mpp.androidSourceSetLayoutVersion1.nowarn=true
можно на Version2 перейти - `kotlin.mpp.androidSourceSetLayoutVersion=2`

2023-02-02 10:46 UTC, aartikov commented on sample/androidSample/build.gradle.kts
> +        minSdk = 26
minSdk = 23 можем поставить? Пока что ее поддерживаем в наших проектах

2023-02-02 10:46 UTC, aartikov commented on sample/androidSample/src/main/java/ru/mobileup/sesame/kmm/android_sample/utils/ResourcesExtensions.kt
> +fun ColorResource.getColor(): ComposeColor {
ColorResource - для цветов, может, moko не будем использовать?

2023-02-02 10:46 UTC, aartikov commented on sample/androidSample/src/main/java/ru/mobileup/sesame/kmm/android_sample/utils/Utils.kt
> +}
По-идее, мы можем эти утилиты поместить в библиотеку (в androidMain). Как считаешь?

2023-02-02 10:46 UTC, aartikov commented on sample/androidSample/src/main/java/ru/mobileup/sesame/kmm/android_sample/utils/Utils.kt
> +fun VisualTransformation.asCompose(): ComposeVisualTransformation {
`asCompose` - давай, переименуем в `toCompose`. Обычно такой нейминг используем в наших проектах

2023-02-02 10:46 UTC, aartikov commented on sample/iosSample/iosSample/Input/VisualFormatter.swift
> +    }
Норм работает?
Не учитывается OffsetMapping. Это не критично?

2023-02-02 10:46 UTC, aartikov commented on sample/sharedSample/build.gradle.kts
> +    }
соурссеты с "test", давай, просто удалим, раз тестов нет

2023-02-02 10:46 UTC, aartikov commented on sample/sharedSample/build.gradle.kts
> +                api(libs.moko.graphics)
Давай, моко только для строк будем использовать?

2023-02-02 10:46 UTC, aartikov commented on sample/sharedSample/build.gradle.kts
> +        minSdk = 26
minSdk = 23

2023-02-02 10:46 UTC, aartikov commented on sample/sharedSample/src/commonMain/kotlin/ru/mobileup/sesame/kmm/sharedsample/App.kt
> +    fun getFormComponent(): FormComponent {
Лучше передать componentContext параметром, чтоб инициализировать его с учетом ЖЦ (см мой каркас). Тут это некритично, но люди будут копипастить это себе на проекты.

2023-02-02 10:46 UTC, aartikov commented on sample/sharedSample/src/commonMain/kotlin/ru/mobileup/sesame/kmm/sharedsample/ui/RealFormComponent.kt
> +}
Сделаем просто enum, без moko

2023-02-02 10:46 UTC, aartikov commented on sample/sharedSample/src/commonMain/kotlin/ru/mobileup/sesame/kmm/sharedsample/ui/RealFormComponent.kt
> +                regex = "[a-zA-Z0-9+._%\\-]{1,256}@[a-zA-Z0-9][a-zA-Z0-9\\-]{0,64}(\\.[a-zA-Z0-9][a-zA-Z0-9\\-]{0,25})+".toRegex(),
лучше вынести regex в константу

2023-02-02 10:46 UTC, aartikov commented on sample/sharedSample/src/commonMain/kotlin/ru/mobileup/sesame/kmm/sharedsample/ui/RealFormComponent.kt
> +            isNotBlank(StringDesc.Resource(Res.strings.field_is_blank_error_message))
Можно использовать краткую версию - `isNotBlank(Res.strings.field_is_blank_error_message)`.

Аналогично в остальных местах

2023-02-02 10:46 UTC, aartikov commented on shared/build.gradle.kts
> +    namespace = "ru.mobileup.sesame.kmm.form"
Сделаем пакет `ru.mobileup.kmm_form_validation`? 
Я не вижу ничего плохого в поддчеркиваниях в именах пакетов. А ты?

2023-02-02 10:46 UTC, aartikov commented on shared/src/commonMain/kotlin/ru/mobileup/sesame/kmm/form/control/CheckControl.kt
> +    val scrollToItEvent get() = mutableScrollToItEventFlow.asSharedFlow().asCSharedFlow()
Кажется, тип может быть просто `CFlow`, а не `CSharedFlow`

2023-02-02 10:46 UTC, aartikov commented on shared/src/commonMain/kotlin/ru/mobileup/sesame/kmm/form/control/CheckControl.kt
> +    //TODO: fix for ios
Какая проблема на iOS?

2023-02-02 10:46 UTC, aartikov commented on shared/src/iosMain/kotlin/ru/mobileup/sesame/kmm/form/IosCoroutineScope.kt
> +val IosCoroutineScope: CoroutineScope = CoroutineScope(Job() + Dispatchers.Main)
вроде нигде не используется

2023-02-02 10:46 UTC, aartikov commented on shared/src/commonMain/kotlin/ru/mobileup/sesame/kmm/state/CMutableStateFlow.kt
> +expect class CMutableStateFlow<T : Any>(initialValue: T) : MutableStateFlow<T>, CStateFlow<T>
Подскажи, для чего нужны разные реализации для Android и iOS?
Я в moko-mvvm видел такое же, но не понял идею.

2023-02-02 10:46 UTC, aartikov commented on sample/iosSample/iosSample/iosSampleApp.swift
> +}
Давай, вынесем FormView в отдельный файл?

2023-02-02 10:46 UTC, aartikov commented on sample/iosSample/iosSample/iosSampleApp.swift
> +    let formComponent: FormComponent
Я не уверен, но кажется поле в App должно быть помечено аннотацией `@StateObject`.
По крайней мере в семпле декомпоза так делают.

Для этого используют вспомогательный класс RootHolder, чтоб поместить в него компонент и lifecycle

2023-02-02 13:22 UTC, Takexito commented on sample/androidSample/build.gradle.kts
> +        minSdk = 26
done

2023-02-03 09:10 UTC, Takexito commented on gradle.properties
> +kotlin.mpp.androidSourceSetLayoutVersion1.nowarn=true
done

2023-02-03 09:10 UTC, Takexito commented on sample/androidSample/src/main/java/ru/mobileup/sesame/kmm/android_sample/utils/ResourcesExtensions.kt
> +fun ColorResource.getColor(): ComposeColor {
done

2023-02-03 09:11 UTC, Takexito commented on sample/androidSample/src/main/java/ru/mobileup/sesame/kmm/android_sample/utils/Utils.kt
> +}
done

2023-02-03 09:11 UTC, Takexito commented on sample/androidSample/src/main/java/ru/mobileup/sesame/kmm/android_sample/utils/Utils.kt
> +fun VisualTransformation.asCompose(): ComposeVisualTransformation {
done

2023-02-03 09:11 UTC, Takexito commented on sample/sharedSample/build.gradle.kts
> +    }
done

2023-02-03 09:11 UTC, Takexito commented on sample/sharedSample/build.gradle.kts
> +                api(libs.moko.graphics)
done

2023-02-03 09:11 UTC, Takexito commented on sample/sharedSample/build.gradle.kts
> +        minSdk = 26
done

2023-02-03 09:11 UTC, Takexito commented on sample/sharedSample/src/commonMain/kotlin/ru/mobileup/sesame/kmm/sharedsample/App.kt
> +    fun getFormComponent(): FormComponent {
done

2023-02-03 09:11 UTC, Takexito commented on sample/sharedSample/src/commonMain/kotlin/ru/mobileup/sesame/kmm/sharedsample/ui/RealFormComponent.kt
> +}
done

2023-02-03 09:11 UTC, Takexito commented on sample/sharedSample/src/commonMain/kotlin/ru/mobileup/sesame/kmm/sharedsample/ui/RealFormComponent.kt
> +                regex = "[a-zA-Z0-9+._%\\-]{1,256}@[a-zA-Z0-9][a-zA-Z0-9\\-]{0,64}(\\.[a-zA-Z0-9][a-zA-Z0-9\\-]{0,25})+".toRegex(),
done

2023-02-03 09:12 UTC, Takexito commented on sample/sharedSample/src/commonMain/kotlin/ru/mobileup/sesame/kmm/sharedsample/ui/RealFormComponent.kt
> +            isNotBlank(StringDesc.Resource(Res.strings.field_is_blank_error_message))
done

2023-02-03 09:12 UTC, Takexito commented on shared/build.gradle.kts
> +    namespace = "ru.mobileup.sesame.kmm.form"
Мне не очень нравятся нижние подчеркивания, но это вкусовщина, поправил

2023-02-03 09:13 UTC, Takexito commented on shared/src/commonMain/kotlin/ru/mobileup/sesame/kmm/form/control/CheckControl.kt
> +    //TODO: fix for ios
Там была проблема с тем, что Unit не был доступен в iOS части

2023-02-03 09:13 UTC, Takexito commented on shared/src/iosMain/kotlin/ru/mobileup/sesame/kmm/form/IosCoroutineScope.kt
> +val IosCoroutineScope: CoroutineScope = CoroutineScope(Job() + Dispatchers.Main)
уже убрано

2023-02-03 09:14 UTC, Takexito commented on shared/src/commonMain/kotlin/ru/mobileup/sesame/kmm/state/CMutableStateFlow.kt
> +expect class CMutableStateFlow<T : Any>(initialValue: T) : MutableStateFlow<T>, CStateFlow<T>
уже убрано

2023-02-03 09:14 UTC, Takexito commented on sample/iosSample/iosSample/iosSampleApp.swift
> +}
done

2023-02-03 09:14 UTC, Takexito commented on sample/iosSample/iosSample/iosSampleApp.swift
> +    let formComponent: FormComponent
Посмотрел примеры, поправил

2023-02-03 09:16 UTC, Takexito commented on sample/iosSample/iosSample/Input/VisualFormatter.swift
> +    }
ну тут немного другой принцип работы, поэтому оффсеты не учитываются

2023-02-07 08:52 UTC, merged